# Generated by Django 5.1 on 2024-09-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_remove_task_author_task_labels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='created_at',
        ),
        migrations.AddField(
            model_name='label',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='labels_for_tasks', to='tasks.task'),
        ),
    ]
