# Generated by Django 5.1 on 2024-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_created_at_label_tasks'),
        ('tasks', '0004_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks_with_labels', to='tasks.task'),
        ),
    ]
