name: build

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Apply migrations
      run: poetry run python manage.py migrate

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: task_manager.settings
        DATABASE_URL: ${{ vars.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: poetry run python3 manage.py test

    - name: Notify deploy to Rollbar
      uses: rollbar/github-deploy-action@2.1.1
      id: rollbar_deploy
      with:
        environment: 'production'
        version: ${{ github.sha }}
        local_username: ${{ github.actor }}
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

